export const tabSwitchInterval:number = 30;
export const MAX_LENGTH_PREVIEW_ORDER_IMAGE:number = 6;


export const AUTH_REQUEST: "AUTH_REQUEST" = "AUTH_REQUEST";
export const AUTH_REQUEST_SUCCESS: "AUTH_REQUEST_SUCCESS" = "AUTH_REQUEST_SUCCESS";
export const AUTH_REQUEST_FAILED: "AUTH_REQUEST_FAILED" = "AUTH_REQUEST_FAILED";
export const USER_REQUEST: "USER_REQUEST" = "USER_REQUEST";
export const USER_REQUEST_SUCCESS: "USER_REQUEST_SUCCESS" = "USER_REQUEST_SUCCESS";
export const USER_REQUEST_FAILED:"USER_REQUEST_FAILED" = "USER_REQUEST_FAILED";
export const USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST" = "USER_UPDATE_REQUEST";
export const USER_UPDATE_REQUEST_SUCCESS: "USER_UPDATE_REQUEST_SUCCESS" = "USER_UPDATE_REQUEST_SUCCESS";
export const USER_UPDATE_REQUEST_FAILED: "USER_UPDATE_REQUEST_FAILED" = "USER_UPDATE_REQUEST_FAILED";
export const LOGOUT_REQUEST: "LOGOUT_REQUEST" = "LOGOUT_REQUEST";
export const LOGOUT_REQUEST_SUCCESS: "LOGOUT_REQUEST_SUCCESS" = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST_FAILED: "LOGOUT_REQUEST_FAILED" = "LOGOUT_REQUEST_FAILED";
export const REGISTER_REQUEST: "REGISTER_REQUEST" = "REGISTER_REQUEST";
export const REGISTER_REQUEST_SUCCESS: "REGISTER_REQUEST_SUCCESS" = "REGISTER_REQUEST_SUCCESS";
export const REGISTER_REQUEST_FAILED: "REGISTER_REQUEST_FAILED" = "REGISTER_REQUEST_FAILED";
export const RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST" = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_REQUEST_SUCCESS: "RESET_PASSWORD_REQUEST_SUCCESS" = "RESET_PASSWORD_REQUEST_SUCCESS";
export const RESET_PASSWORD_REQUEST_FAILED: "RESET_PASSWORD_REQUEST_FAILED" = "RESET_PASSWORD_REQUEST_FAILED";
export const SEND_PASSWORD_REQUEST: "SEND_PASSWORD_REQUEST" = "SEND_PASSWORD_REQUEST";
export const SEND_PASSWORD_REQUEST_SUCCESS: "SEND_PASSWORD_REQUEST_SUCCESS" = "SEND_PASSWORD_REQUEST_SUCCESS";
export const SEND_PASSWORD_REQUEST_FAILED: "SEND_PASSWORD_REQUEST_FAILED" = "SEND_PASSWORD_REQUEST_FAILED";
export const CLEAR_RESET_PASSWORD_REQUEST: "CLEAR_RESET_PASSWORD_REQUEST" = "CLEAR_RESET_PASSWORD_REQUEST";
export const REFRESH_TOKEN_REQUEST: "REFRESH_TOKEN_REQUEST" = "REFRESH_TOKEN_REQUEST";
export const REFRESH_TOKEN_REQUEST_SUCCESS: "REFRESH_TOKEN_REQUEST_SUCCESS" = "REFRESH_TOKEN_REQUEST_SUCCESS";
export const REFRESH_TOKEN_REQUEST_FAILED: "REFRESH_TOKEN_REQUEST_FAILED" = "REFRESH_TOKEN_REQUEST_FAILED";


export const CONSTRUCTOR_ADD: "CONSTRUCTOR_ADD" = "CONSTRUCTOR_ADD";
export const CONSTRUCTOR_DELETE: "CONSTRUCTOR_DELETE" = "CONSTRUCTOR_DELETE";
export const CONSTRUCTOR_RESET: "CONSTRUCTOR_RESET" = "CONSTRUCTOR_RESET";
export const CONSTRUCTOR_REORDER: "CONSTRUCTOR_REORDER" = "CONSTRUCTOR_REORDER";

export const DATA_REQUEST: "DATA_REQUEST" = "DATA_REQUEST";
export const DATA_REQUEST_SUCCESS: "DATA_REQUEST_SUCCESS" = "DATA_REQUEST_SUCCESS";
export const DATA_REQUEST_FAILED: "DATA_REQUEST_FAILED" = "DATA_REQUEST_FAILED";
export const DECREASE_COUNT: "DECREASE_COUNT" = "DECREASE_COUNT";
export const INCREASE_COUNT: "INCREASE_COUNT" = "INCREASE_COUNT";
export const RESET_COUNT:"RESET_COUNT" = "RESET_COUNT";

export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST'= "CREATE_ORDER_REQUEST";
export const CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS" = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_FAILED: "CREATE_ORDER_FAILED" = "CREATE_ORDER_FAILED";
export const ORDER_RESET: "ORDER_RESET" = "ORDER_RESET";

export const WS_CONNECT: "WS_CONNECT" = "WS_CONNECT";
export const WS_DISCONNECT: "WS_DISCONNECT" = "WS_DISCONNECT";
export const WS_USER_ORDERS_CONNECTING: "WS_USER_ORDERS_CONNECTING" =
  "WS_USER_ORDERS_CONNECTING";
export const WS_USER_ORDERS_OPEN: "WS_USER_ORDERS_OPEN" = "WS_USER_ORDERS_OPEN";
export const WS_USER_ORDERS_CLOSE: "WS_USER_ORDERS_CLOSE" =
  "WS_USER_ORDERS_CLOSE";
export const WS_ORDERS_MESSAGE: "WS_ORDERS_MESSAGE" = "WS_ORDERS_MESSAGE";
export const WS_USER_ORDERS_ERROR: "WS_USER_ORDERS_ERROR" =
  "WS_USER_ORDERS_ERROR";
export const SINGLE_ORDER_REQUEST: "SINGLE_ORDER_REQUEST" =
  "SINGLE_ORDER_REQUEST";
export const SINGLE_ORDER_REQUEST_SUCCESS: "SINGLE_ORDER_REQUEST_SUCCESS" =
  "SINGLE_ORDER_REQUEST_SUCCESS";
export const SINGLE_ORDER_REQUEST_FAILED: "SINGLE_ORDER_REQUEST_FAILED" =
  "SINGLE_ORDER_REQUEST_FAILED";
export const WS_ALL_ORDERS_CLOSE: "WS_ALL_ORDERS_CLOSE" = "WS_ALL_ORDERS_CLOSE";
export const WS_ALL_ORDERS_CONNECTING: "WS_ALL_ORDERS_CONNECTING" =
  "WS_ALL_ORDERS_CONNECTING";
export const WS_ALL_ORDERS_ERROR: "WS_ALL_ORDERS_ERROR" = "WS_ALL_ORDERS_ERROR";
export const WS_ALL_ORDERS_OPEN: "WS_ALL_ORDERS_OPEN" = "WS_ALL_ORDERS_OPEN";